name: Update Game of Life Game

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-game:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: apoupon/gh-game-of-life@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-path: 'game.gif'
          strategy: 'loop'